/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facturacion;

import javax.naming.LimitExceededException;
import javax.swing.JOptionPane;

/**
 *
 * @author Rainy
 */
public class GastosPersonalesRegistro extends javax.swing.JFrame {

    /**
     * Creates new form GastosPersonales
     */
    
    control_existencias control = new control_existencias();
    public GastosPersonalesRegistro() 
    {
        initComponents();
        bloquearCajas();
        btnIngresar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTipoGasto = new javax.swing.JLabel();
        lblFraccionBasicaDesgravada = new javax.swing.JLabel();
        txtFraccionDesgravada = new javax.swing.JTextField();
        lblSalarioBasico = new javax.swing.JLabel();
        txtSalarioBasico = new javax.swing.JTextField();
        lblAnio = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cmbTipoGasto = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTipoGasto.setText("Tipo Gasto");

        lblFraccionBasicaDesgravada.setText("Fracción Básica Desgravada");

        lblSalarioBasico.setText("Salario Básico Anual");

        lblAnio.setText("Año");

        txtAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        cmbTipoGasto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alimentacion", "Vestimenta", "Salud", "Educacion", "Vivienda" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(btnIngresar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtAnio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                        .addComponent(lblAnio, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtSalarioBasico, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblSalarioBasico, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtFraccionDesgravada, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblFraccionBasicaDesgravada, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTipoGasto, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(cmbTipoGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(341, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblTipoGasto)
                .addGap(18, 18, 18)
                .addComponent(cmbTipoGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lblFraccionBasicaDesgravada)
                .addGap(18, 18, 18)
                .addComponent(txtFraccionDesgravada, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSalarioBasico)
                .addGap(18, 18, 18)
                .addComponent(txtSalarioBasico, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAnio)
                .addGap(18, 18, 18)
                .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnIngresar)
                    .addComponent(btnCancelar))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        desbloquearCajas();
        btnIngresar.setEnabled(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        if((!(cmbTipoGasto.getSelectedIndex()==-1))&&(!txtFraccionDesgravada.getText().isEmpty())&&(!txtSalarioBasico.getText().isEmpty())&&(!txtAnio.getText().isEmpty()))
        {
            String tipoGasto,  anio;
            double fraccion, salarioBasico;
            tipoGasto = cmbTipoGasto.getSelectedItem().toString();
            fraccion = Double.parseDouble(txtFraccionDesgravada.getText());
            salarioBasico = Double.parseDouble(txtSalarioBasico.getText());
            anio = txtAnio.getText();
            
            double limite;
            
            if(tipoGasto.equals("Alimentacion")|| tipoGasto.equals("Vestimenta")||tipoGasto.equals("Educacion")||tipoGasto.equals("Vivienda"))
            {
                limite = fraccion*0.325;
            }
            else
            {
                limite = fraccion*1.3;
            }
            String limiteGasto = Double.toString(limite);
            String datos[] = {tipoGasto, limiteGasto, anio};
            boolean insertar = control.getSentencia().insertar(datos, "insert into tipo_gasto_personal(tipo_gasto, limite_gasto, Anio) values (?,?,?)");
            if(insertar)
            {
                JOptionPane.showMessageDialog(null, "Se ha insertado el gasto exitosamente", "Proceso exitoso", JOptionPane.INFORMATION_MESSAGE);
                limpiar();
                bloquearCajas();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "No se ha podido ingresar el gasto", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "No ha ingresado todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limpiar();
        bloquearCajas();
    }//GEN-LAST:event_btnCancelarActionPerformed
    
    
    public void limpiar()
    {
        cmbTipoGasto.setSelectedItem(-1);
        txtFraccionDesgravada.setText("");
        txtSalarioBasico.setText("");
        txtAnio.setText("");
    }
    
    public void bloquearCajas()
    {
        cmbTipoGasto.setEnabled(false);
        txtFraccionDesgravada.setEnabled(false);
        txtSalarioBasico.setEnabled(false);
        txtAnio.setEnabled(false);
    }
    
    public void desbloquearCajas()
    {
        cmbTipoGasto.setEnabled(true);
        txtFraccionDesgravada.setEnabled(true);
        txtSalarioBasico.setEnabled(true);
        txtAnio.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GastosPersonalesRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GastosPersonalesRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GastosPersonalesRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GastosPersonalesRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GastosPersonalesRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox cmbTipoGasto;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblFraccionBasicaDesgravada;
    private javax.swing.JLabel lblSalarioBasico;
    private javax.swing.JLabel lblTipoGasto;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtFraccionDesgravada;
    private javax.swing.JTextField txtSalarioBasico;
    // End of variables declaration//GEN-END:variables
}
