package facturacion;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class GastosPersonalesEdicion extends javax.swing.JFrame {

    /**
     * Creates new form GastosPersonalesEdicion
     */
    
    control_existencias controlExistencias = new control_existencias();
    public GastosPersonalesEdicion() {
        initComponents();
        btnEditar.setEnabled(false);
        
        Object[] tipoGasto = controlExistencias.combox("gastos_personales","tipo_gasto");
        cmbTipoGasto.removeAllItems();
        for(int i =0;i<tipoGasto.length;i++)
        {
            cmbTipoGasto.addItem(tipoGasto[i]);
        }
        cmbTipoGasto.setSelectedIndex(-1);
        btnEditar.setEnabled(false);
        bloquearCajas();
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        lblTipoGasto = new javax.swing.JLabel();
        cmbTipoGasto = new javax.swing.JComboBox();
        lblLimiteGasto = new javax.swing.JLabel();
        txtLimiteGasto = new javax.swing.JTextField();
        lblAcumulado = new javax.swing.JLabel();
        txtAcumulado = new javax.swing.JTextField();
        lblAnio = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTipoGasto.setText("Tipo de gasto");

        cmbTipoGasto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblLimiteGasto.setText("Límite de gasto");

        lblAcumulado.setText("Acumulado");

        lblAnio.setText("Año");

        txtAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnio)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLimiteGasto)
                            .addComponent(lblTipoGasto)
                            .addComponent(cmbTipoGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLimiteGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAcumulado)
                            .addComponent(txtAcumulado, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblTipoGasto)
                .addGap(18, 18, 18)
                .addComponent(cmbTipoGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLimiteGasto)
                    .addComponent(lblAcumulado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAcumulado, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(txtLimiteGasto))
                .addGap(18, 18, 18)
                .addComponent(lblAnio)
                .addGap(18, 18, 18)
                .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnEditar)
                    .addComponent(btnCancelar))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        
        if(cmbTipoGasto.getSelectedIndex()==-1)
        {
             JOptionPane.showMessageDialog(null, "No ha seleccionado un tipo de gasto a editar", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            String tipoGasto = cmbTipoGasto.getSelectedItem().toString();
            String[] colName = {"id_tipo_gasto","tipo_gasto", "limite_gasto", "acumulado_a_fecha", "diferencia", "Anio"};
            Object[][] gasto = controlExistencias.getSentencia().GetTabla(colName, "gastos_personales", "select * from gastos_personales where tipo_gasto='"+tipoGasto+"'");
            txtLimiteGasto.setText(gasto[0][2].toString());
            txtAcumulado.setText(gasto[0][3].toString());
            txtAnio.setText(gasto[0][5].toString());
            desbloquearCajas();
            btnEditar.setEnabled(true);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        if((!txtAcumulado.getText().isEmpty())&&(!txtAnio.getText().isEmpty())&&(!txtLimiteGasto.getText().isEmpty()))
        {
            String acumulado, anio, limiteGasto;
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "No ha ingresado los datos a modificar", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limpiar();
        bloquearCajas();
    }//GEN-LAST:event_btnCancelarActionPerformed

    
    public void limpiar()
    {
        cmbTipoGasto.setSelectedIndex(-1);
        txtAcumulado.setText("");
        txtAnio.setText("");
        txtLimiteGasto.setText("");
    }
    
    public void bloquearCajas()
    {
        txtAcumulado.setEnabled(false);
        txtAnio.setEnabled(false);
        txtLimiteGasto.setEnabled(false);
    }
    
    public void desbloquearCajas()
    {
        txtAcumulado.setEnabled(true);
        txtAnio.setEnabled(true);
        txtLimiteGasto.setEnabled(true);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GastosPersonalesEdicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GastosPersonalesEdicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GastosPersonalesEdicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GastosPersonalesEdicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GastosPersonalesEdicion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JComboBox cmbTipoGasto;
    private javax.swing.JLabel lblAcumulado;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblLimiteGasto;
    private javax.swing.JLabel lblTipoGasto;
    private javax.swing.JTextField txtAcumulado;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtLimiteGasto;
    // End of variables declaration//GEN-END:variables
}