package facturacion;

import javax.swing.JOptionPane;


public class Interfaz_Clientes1 extends javax.swing.JFrame {

    
    control_existencias controlExistencias = new control_existencias();
    public Interfaz_Clientes1() {
        initComponents();
        limpiar();
        bloquearCajas();
        txtDocumento.setEnabled(true);
        btnCancelar.setEnabled(false);
        btnEditarRegistro.setEnabled(false);
        btnRegistrar.setEnabled(false);
        Object[] tipo_doc = controlExistencias.combox("tipo_de_documento","Descripcion");
        cmbTipoDocumento.removeAllItems();
        for(int i=0;i<tipo_doc.length;i++)
            cmbTipoDocumento.addItem(tipo_doc[i]);
        
        Object[] ciu = controlExistencias.combox("ciudad","Nombre_ciudad");
        cmbCiudad.removeAllItems();
        for(int i=0;i<ciu.length;i++)
            cmbCiudad.addItem(ciu[i]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDocumento = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        lblTipoDocumento = new javax.swing.JLabel();
        cmbTipoDocumento = new javax.swing.JComboBox();
        lblNombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblCiudad = new javax.swing.JLabel();
        cmbCiudad = new javax.swing.JComboBox();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        btnNUevoRegistro = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblContraseña = new javax.swing.JLabel();
        lblConfirmarContrasenia = new javax.swing.JLabel();
        btnEditarRegistro = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtContrasenia = new javax.swing.JPasswordField();
        txtConfirmarContrasenia = new javax.swing.JPasswordField();

        lblDocumento.setText("Documento");

        lblTipoDocumento.setText("Tipo de documento");

        cmbTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblNombres.setText("Nombres");

        lblApellidos.setText("Apelliidos");
        lblApellidos.setName(""); // NOI18N

        lblDireccion.setText("Dirección");

        lblCiudad.setText("Ciudad");

        cmbCiudad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblTelefono.setText("Teléfono");

        btnNUevoRegistro.setText("Nuevo Registro");
        btnNUevoRegistro.setName(""); // NOI18N
        btnNUevoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNUevoRegistroActionPerformed(evt);
            }
        });

        btnRegistrar.setLabel("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnCancelar.setLabel("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalir.setLabel("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblContraseña.setText("Contraseña");
        lblContraseña.setToolTipText("Mínimo 6 caracteres, una letra, un número y un caracter especial (*,_,-)");

        lblConfirmarContrasenia.setText("Confirmar Contraseña");

        btnEditarRegistro.setText("Editar Registro");
        btnEditarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarRegistroActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefono))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addGap(29, 29, 29)
                                .addComponent(btnEditarRegistro)
                                .addGap(18, 18, 18)
                                .addComponent(btnNUevoRegistro)
                                .addGap(18, 18, 18)
                                .addComponent(btnRegistrar)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalir))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtContrasenia)
                                        .addGap(71, 71, 71))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lblDocumento)
                                                .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblNombres)
                                                .addComponent(lblDireccion)
                                                .addComponent(txtNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                                                .addComponent(txtDireccion))
                                            .addComponent(lblContraseña))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblConfirmarContrasenia)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblCiudad)
                                        .addComponent(lblApellidos)
                                        .addComponent(cmbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                        .addComponent(cmbTipoDocumento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblTipoDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtConfirmarContrasenia)))))
                        .addGap(54, 54, 54))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocumento)
                    .addComponent(lblTipoDocumento))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDocumento)
                    .addComponent(cmbTipoDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombres)
                    .addComponent(lblApellidos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(txtApellidos))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(lblCiudad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(cmbCiudad))
                .addGap(60, 60, 60)
                .addComponent(lblTelefono)
                .addGap(18, 18, 18)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContraseña)
                    .addComponent(lblConfirmarContrasenia))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConfirmarContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNUevoRegistro)
                    .addComponent(btnRegistrar)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalir)
                    .addComponent(btnEditarRegistro)
                    .addComponent(btnBuscar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNUevoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNUevoRegistroActionPerformed
        // TODO add your handling code here:
        desbloquearCajas();
        btnBuscar.setEnabled(false);
        btnRegistrar.setEnabled(true);
    }//GEN-LAST:event_btnNUevoRegistroActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        
        if((txtContrasenia.getText().equals(txtConfirmarContrasenia.getText()))&&(txtContrasenia.getText().matches("[a-zA-Z0-9_-]+{6,20}")))
        {
            String doc,nom,ape,dir,ciu,tipo,tel, contraseña;
        
            String index1, index2;
            String[] columna= {"id_tipo_documento"};
            index1 = (String)controlExistencias.getSentencia().GetTabla(columna, "tipo_de_documento", "select id_tipo_documento from tipo_de_documento where Descripcion='"+cmbTipoDocumento.getSelectedItem()+"';")[0][0];

            doc = txtDocumento.getText();
            tipo= index1;
            nom = txtNombres.getText();
            ape = txtApellidos.getText();
            dir = txtDireccion.getText();
            contraseña = txtContrasenia.getText();

            String[] columna1 = {"Codigo_ciudad"};
            index2 = (String)controlExistencias.getSentencia().GetTabla(columna1, "ciudad", "select Codigo_ciudad from ciudad where Nombre_ciudad='"+cmbCiudad.getSelectedItem()+"';")[0][0];
            ciu = index2;
            tel = txtTelefono.getText();
            control_cliente contr = new control_cliente(doc, tipo, nom, ape, dir, ciu,tel, contraseña);
            if(!doc.equals("") && !tipo.equals("") && !nom.equals("") && !ape.equals("") )
            {
                if(contr.ingresar_cliente())
                {
                    JOptionPane.showMessageDialog(null,"El cliente se registro con exito ","Mensaje",JOptionPane.INFORMATION_MESSAGE);
                    limpiar();
                    bloquearCajas();
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Error al registrar el cliente");
                }
            }
            else
            {
              JOptionPane.showMessageDialog(this, "Hay campos obligatorios");  
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden o no cumplen con los requisitos", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limpiar();
        bloquearCajas();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarRegistroActionPerformed
        // TODO add your handling code here:
        
        String doc,nom,ape,dir,ciu,tipo,tel, contrasenia;
        if((txtContrasenia.getText().equals(txtConfirmarContrasenia.getText()))&&(txtContrasenia.getText().matches("[a-zA-Z0-9]+{6,20}")))
        {
            if((!txtApellidos.getText().isEmpty())&&(!txtNombres.getText().isEmpty())&&(!txtDireccion.getText().isEmpty()))
            {
                doc = txtDocumento.getText();
                nom = txtNombres.getText();
                ape = txtApellidos.getText();
                dir = txtDireccion.getText();
                ciu = cmbCiudad.getSelectedItem().toString();
                tipo = cmbTipoDocumento.getSelectedItem().toString();
                tel = txtTelefono.getText();
                contrasenia = txtContrasenia.getText();
                control_cliente ctrlCliente = new control_cliente(doc, tipo, nom, ape, dir, ciu, tel, contrasenia);
                if(ctrlCliente.actualizar_cliente())
                {
                    JOptionPane.showMessageDialog(null, "Usuario actualizado exitosamente", "Proceso exitoso", JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Error al actualizar información de usuario","Error", JOptionPane.ERROR_MESSAGE );
                }
                String[] colName = {"Documento", "cod_tipo_documento", "Nombres", "Apellidos", "Direccion", "cod_ciudad", "Telefono", "Contraseña"};
            }
            else
            {
                JOptionPane.showMessageDialog(null, "NO ha ingresado todos los datos", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnEditarRegistroActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        desbloquearCajas();
        btnRegistrar.setEnabled(false);
        if(txtDocumento.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "No ha ingresado un documento", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
                btnEditarRegistro.setEnabled(true);
                String tipoDocumento, ciudad;
                String[] colName = {"Documento", "cod_tipo_documento", "Nombres", "Apellidos", "Direccion", "cod_ciudad", "Telefono", "Contraseña"};
                Object[][] GetTabla = controlExistencias.getSentencia().GetTabla(colName, "cliente", "select * from cliente where Documento='"+txtDocumento.getText()+"'");
                txtNombres.setText(GetTabla[0][2].toString());
                txtApellidos.setText(GetTabla[0][3].toString());
                txtDireccion.setText(GetTabla[0][4].toString());
                txtTelefono.setText(GetTabla[0][6].toString());
                txtContrasenia.setText(GetTabla[0][7].toString());
                txtConfirmarContrasenia.setText(GetTabla[0][7].toString());

                String[] colTipo = {"Descripcion"};
                Object[][] tipo_Documento = controlExistencias.getSentencia().GetTabla(colTipo, "tipo_de_documento", "select Descripcion from tipo_de_documento where id_tipo_documento='"+GetTabla[0][1]+"'");
                cmbTipoDocumento.setSelectedItem(tipo_Documento);

                String[] colCiudad = {"Nombre_ciudad"};
                Object[][] nombreCiudad = controlExistencias.getSentencia().GetTabla(colCiudad, "ciudad", "select Nombre_ciudad from ciudad where codigo_ciudad='"+GetTabla[0][5]+"'");
                cmbCiudad.setSelectedItem(tipo_Documento);
            
        }
    }//GEN-LAST:event_btnBuscarActionPerformed
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger("error", null);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger("error", null);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger("error", null);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger("error", null);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Clientes1().setVisible(true);
            }
        });
    }
    
    public void limpiar()
    {
        txtApellidos.setText("");
        txtDireccion.setText("");
        txtDocumento.setText("");
        txtNombres.setText("");
        txtTelefono.setText("");
        cmbCiudad.setSelectedIndex(0);
        cmbTipoDocumento.setSelectedIndex(0);
        txtContrasenia.setText("");
        txtConfirmarContrasenia.setText("");
        
    }
    
    public void bloquearCajas()
    {
        txtApellidos.setEnabled(false);
        txtConfirmarContrasenia.setEnabled(false);
        txtContrasenia.setEnabled(false);
        txtNombres.setEnabled(false);
        txtDireccion.setEnabled(false);
        txtDocumento.setEnabled(false);
        txtNombres.setEnabled(false);
        txtTelefono.setEnabled(false);
        cmbCiudad.setEnabled(false);
        cmbTipoDocumento.setEnabled(false);
    }
    
    public void desbloquearCajas()
    {
        txtApellidos.setEnabled(true);
        txtConfirmarContrasenia.setEnabled(true);
        txtContrasenia.setEnabled(true);
        txtNombres.setEnabled(true);
        txtDireccion.setEnabled(true);
        txtDocumento.setEnabled(true);
        txtNombres.setEnabled(true);
        txtTelefono.setEnabled(true);
        cmbCiudad.setEnabled(true);
        cmbTipoDocumento.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditarRegistro;
    private javax.swing.JButton btnNUevoRegistro;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cmbCiudad;
    private javax.swing.JComboBox cmbTipoDocumento;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblConfirmarContrasenia;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDocumento;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTipoDocumento;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JPasswordField txtConfirmarContrasenia;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
