/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facturacion;

import javax.swing.JOptionPane;

/**
 *
 * @author Rainy
 */
public class InterfazClasificacionFacturasXML extends javax.swing.JFrame {

    /**
     * Creates new form InterfazClasificacionFacturasXML
     */
    
    control_existencias controlExistencias = new control_existencias();
    public InterfazClasificacionFacturasXML() {
        initComponents();
        cmbDetallesFactura.setEnabled(false);
        cmbTipoGasto.setEnabled(false);
        btnIngresarGastos.setEnabled(false);
        cmbDetallesFactura.removeAllItems();
        cmbTipoGasto.removeAllItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpTipoFactura = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        rbtGastosNegocio = new javax.swing.JRadioButton();
        rbtGastosPersonales = new javax.swing.JRadioButton();
        btnIngresarGastos = new javax.swing.JButton();
        btnNuevaFactura = new javax.swing.JButton();
        lblDetallesFactura = new javax.swing.JLabel();
        lblTipoGasto = new javax.swing.JLabel();
        cmbDetallesFactura = new javax.swing.JComboBox();
        cmbTipoGasto = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        grpTipoFactura.add(rbtGastosNegocio);
        rbtGastosNegocio.setText("Gastos de Negocio");

        grpTipoFactura.add(rbtGastosPersonales);
        rbtGastosPersonales.setText("Gastos Personales");

        btnIngresarGastos.setText("Ingresar Gastos");
        btnIngresarGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarGastosActionPerformed(evt);
            }
        });

        btnNuevaFactura.setText("Nueva Factura");
        btnNuevaFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaFacturaActionPerformed(evt);
            }
        });

        lblDetallesFactura.setText("Detalles de Factura");

        lblTipoGasto.setText("Tipo de Gasto");

        cmbDetallesFactura.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbTipoGasto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtGastosNegocio)
                    .addComponent(btnNuevaFactura)
                    .addComponent(lblDetallesFactura)
                    .addComponent(cmbDetallesFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIngresarGastos)
                    .addComponent(rbtGastosPersonales)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cmbTipoGasto, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTipoGasto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtGastosNegocio)
                    .addComponent(rbtGastosPersonales))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDetallesFactura)
                    .addComponent(lblTipoGasto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDetallesFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresarGastos)
                    .addComponent(btnNuevaFactura))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaFacturaActionPerformed
        // TODO add your handling code here:
        if(grpTipoFactura.getSelection().isSelected())
        {
            if(rbtGastosNegocio.isSelected())
            {
                cmbDetallesFactura.setEnabled(true);
                cmbTipoGasto.setEnabled(true);
                Object[] tipo_doc = controlExistencias.combox("tipo_gasto_negocio","descripcion_tipo_gasto_negocio");
                for(int i=0;i<tipo_doc.length;i++)
                    cmbTipoGasto.addItem(tipo_doc[i]);
            }
            else if(rbtGastosPersonales.isSelected())
            {
               cmbTipoGasto.addItem("Alimentación");
               cmbTipoGasto.addItem("Vestimenta");
               cmbTipoGasto.addItem("Salud");
               cmbTipoGasto.addItem("Educación");
               cmbTipoGasto.addItem("Vivienda");
               cmbTipoGasto.addItem("Otros");
               
            }
            else
            {
                JOptionPane.showMessageDialog(null, "No ha seleccionado el tipo de factura","Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnNuevaFacturaActionPerformed

    private void btnIngresarGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarGastosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarGastosActionPerformed

    public void limpiarCajas()
    {
        grpTipoFactura.clearSelection();
        cmbDetallesFactura.setSelectedIndex(-1);
        cmbTipoGasto.setSelectedIndex(-1);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazClasificacionFacturasXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazClasificacionFacturasXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazClasificacionFacturasXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazClasificacionFacturasXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazClasificacionFacturasXML().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarGastos;
    private javax.swing.JButton btnNuevaFactura;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox cmbDetallesFactura;
    private javax.swing.JComboBox cmbTipoGasto;
    private javax.swing.ButtonGroup grpTipoFactura;
    private javax.swing.JLabel lblDetallesFactura;
    private javax.swing.JLabel lblTipoGasto;
    private javax.swing.JRadioButton rbtGastosNegocio;
    private javax.swing.JRadioButton rbtGastosPersonales;
    // End of variables declaration//GEN-END:variables
}
